import React, { useCallback, useEffect, useRef, useState } from "react";
import { Alert, FlatList, Modal, Pressable, ScrollView, StyleSheet, Switch, Text, View } from "react-native";
import * as Location from "expo-location";
import { CameraView, useCameraPermissions } from "expo-camera";
import { BottomTabScreenProps } from "@react-navigation/bottom-tabs";
import { NativeStackScreenProps } from "@react-navigation/native-stack";
import { api, apiBaseUrl, login, logout, setApiBaseUrl } from "@/api/client";
import { addPhoto, cacheSchema, cachedSchema, dashboardCounts, getPreSurvey, records, savePreSurvey, saveRecord } from "@/db";
import { Button, Field, GlassCard, Header, Label } from "@/components/UI";
import { useTheme } from "@/context/ThemeContext";
import { FormSchema, Question, SurveyRecord } from "@/types";
import { syncPending } from "@/sync/engine";

type RootStack = { Login: undefined; PreSurvey: undefined; Main: undefined; SurveyType: undefined; Category: { module: string }; DynamicForm: { module: string; category: string } };
export type Tabs = { Dashboard: undefined; Surveys: undefined; Sync: undefined; Settings: undefined };
type StackProps<N extends keyof RootStack> = NativeStackScreenProps<RootStack, N>;
type TabProps<N extends keyof Tabs> = BottomTabScreenProps<Tabs, N>;
const fallback: FormSchema = { version: 1, questions: [{ id: "chainage", label: "Chainage", type: "text", required: true }, { id: "structure_name", label: "Structure name", type: "text", required: true }, { id: "condition", label: "Condition rating", type: "condition_rating", required: true, options: ["Good", "Fair", "Poor"] }, { id: "photos", label: "Structure photographs", type: "photo_group", required: true, minPhotos: 4 }] };
const categories = ["Culvert", "Minor Bridge", "Major Bridge", "ROB / RUB", "Causeway", "Retaining Wall"];
function Screen({ children }: React.PropsWithChildren) { const { theme } = useTheme(); return <View style={[styles.screen, { backgroundColor: theme.background }]}><Header /><ScrollView contentContainerStyle={styles.content}>{children}</ScrollView></View>; }

export function LoginScreen({ navigation }: StackProps<"Login">) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [loading, setLoading] = useState(false);
  const signIn = async () => { try { setLoading(true); await login(email, password); navigation.replace("PreSurvey"); } catch { Alert.alert("Sign in failed", "Check your credentials and API URL."); } finally { setLoading(false); } };
  return <Screen><GlassCard><Text style={styles.hero}>Field survey, even offline.</Text><Label>Email</Label><Field value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="surveyor@gdrpl.in" /><Label>Password</Label><Field value={password} onChangeText={setPassword} secureTextEntry placeholder="••••••••" /><Button title={loading ? "Signing in…" : "Sign in"} onPress={signIn} disabled={loading} /></GlassCard></Screen>;
}
export function PreSurveyScreen({ navigation }: StackProps<"PreSurvey">) {
  const [values, setValues] = useState({ headSurveyor: "", organization: "", projectName: "", projectNumber: "", highwayNumber: "" });
  useEffect(() => { getPreSurvey().then(row => { if (row) setValues({ headSurveyor: row.head_surveyor, organization: row.organization, projectName: row.project_name, projectNumber: row.project_number, highwayNumber: row.highway_number }); }); }, []);
  const update = (key: keyof typeof values) => (value: string) => setValues(v => ({ ...v, [key]: value }));
  const save = async () => { if (Object.values(values).some(v => !v.trim())) return Alert.alert("Complete all fields"); await savePreSurvey(values); navigation.replace("Main"); };
  return <Screen><GlassCard><Text style={styles.hero}>Project briefing</Text>{([["headSurveyor", "Head Surveyor"], ["organization", "Organization"], ["projectName", "Project Name"], ["projectNumber", "Project Number"], ["highwayNumber", "Highway Number"]] as const).map(([key, label]) => <View key={key}><Label>{label}</Label><Field value={values[key]} onChangeText={update(key)} /></View>)}<Button title="Save project details" onPress={save} /></GlassCard></Screen>;
}
export function SurveyTypeScreen({ navigation }: StackProps<"SurveyType">) { return <Screen><Text style={styles.hero}>Choose survey type</Text>{[["structure_inventory", "Structure Inventory"], ["utility_shifting", "Utility Shifting"]].map(([module, title]) => <Pressable key={module} onPress={() => navigation.navigate("Category", { module })}><GlassCard style={styles.choice}><Text style={styles.choiceText}>{title}</Text><Text>Start a new field record →</Text></GlassCard></Pressable>)}</Screen>; }
export function CategoryScreen({ navigation, route }: StackProps<"Category">) { const { module } = route.params; return <Screen><Text style={styles.hero}>Structure category</Text>{categories.map(category => <Pressable key={category} onPress={() => navigation.navigate("DynamicForm", { module, category })}><GlassCard style={styles.category}><Text style={styles.choiceText}>{category}</Text></GlassCard></Pressable>)}</Screen>; }

export function DynamicFormScreen({ route, navigation }: StackProps<"DynamicForm">) {
  const [schema, setSchema] = useState<FormSchema>(fallback); const [answers, setAnswers] = useState<Record<string, unknown>>({}); const [photos, setPhotos] = useState<string[]>([]); const [cameraOpen, setCameraOpen] = useState(false); const [permission, requestPermission] = useCameraPermissions(); const [coords, setCoords] = useState<Location.LocationObjectCoords | null>(null); const cameraRef = useRef<CameraView>(null);
  useEffect(() => { (async () => { try { const { data } = await api.get(`/api/schemas/${route.params.module}/active`); const result = { version: data.version, questions: data.schema_json.questions ?? data.schema_json.fields ?? [] }; setSchema(result); await cacheSchema(route.params.module, data.version, result); } catch { const cached = await cachedSchema(route.params.module); if (cached) setSchema(JSON.parse(cached.schema_json)); } const locationPermission = await Location.requestForegroundPermissionsAsync(); if (locationPermission.status === "granted") setCoords((await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.Balanced })).coords); })(); }, [route.params.module]);
  const setAnswer = (id: string, value: unknown) => setAnswers(v => ({ ...v, [id]: value }));
  const capture = async (camera: CameraView | null) => { const photo = await camera?.takePictureAsync({ quality: .7 }); if (photo?.uri) { setPhotos(p => [...p, photo.uri]); setCameraOpen(false); } };
  const submit = async () => { const required = schema.questions.filter(q => q.required && q.type !== "photo_group"); if (required.some(q => !answers[q.id])) return Alert.alert("Complete required fields"); const minimum = schema.questions.find(q => q.type === "photo_group")?.minPhotos ?? 4; if (photos.length < minimum) return Alert.alert("More photos required", `Capture at least ${minimum} photos.`); const record: SurveyRecord = { id: crypto.randomUUID(), module: route.params.module, category: route.params.category, chainage: String(answers.chainage ?? ""), responses: { ...answers, gps: coords ? { latitude: coords.latitude, longitude: coords.longitude } : null, capturedAt: new Date().toISOString() }, latitude: coords?.latitude, longitude: coords?.longitude, capturedAt: new Date().toISOString(), status: "submitted", syncStatus: "pending", schemaVersion: schema.version }; await saveRecord(record); for (const uri of photos) await addPhoto(record.id, uri); Alert.alert("Saved locally", "The completed record is ready to sync.", [{ text: "Done", onPress: () => navigation.popToTop() }]); };
  const renderQuestion = (q: Question) => { if (q.type === "photo_group") return <View key={q.id}><Label>{q.label} ({photos.length}/{q.minPhotos ?? 4})</Label><Button title="Open camera" onPress={async () => { if (!permission?.granted) await requestPermission(); setCameraOpen(true); }} /></View>; if (q.type === "select" || q.type === "condition_rating") return <View key={q.id}><Label>{q.label}</Label><View style={styles.options}>{(q.options ?? []).map(option => <Pressable key={option} onPress={() => setAnswer(q.id, option)} style={[styles.pill, answers[q.id] === option && styles.selected]}><Text>{option}</Text></Pressable>)}</View></View>; if (q.type === "multiselect") return <View key={q.id}><Label>{q.label}</Label><View style={styles.options}>{(q.options ?? []).map(option => { const selected = ((answers[q.id] as string[]) ?? []).includes(option); return <Pressable key={option} onPress={() => setAnswer(q.id, selected ? ((answers[q.id] as string[]).filter(x => x !== option)) : [...((answers[q.id] as string[]) ?? []), option])} style={[styles.pill, selected && styles.selected]}><Text>{option}</Text></Pressable>; })}</View></View>; if (q.type === "date") return <View key={q.id}><Label>{q.label}</Label><Field editable={false} value={new Date().toLocaleString()} /></View>; return <View key={q.id}><Label>{q.label}{q.required ? " *" : ""}</Label><Field value={String(answers[q.id] ?? "")} onChangeText={v => setAnswer(q.id, v)} keyboardType={q.type === "number" ? "numeric" : "default"} /></View>; };
  return <Screen><View style={styles.formRow}><View style={styles.rail}><View style={[styles.railFill, { height: `${Math.min(100, Object.keys(answers).length / Math.max(schema.questions.length - 1, 1) * 100)}%` }]} /></View><GlassCard style={styles.form}><Text style={styles.hero}>{route.params.category}</Text><Text style={styles.meta}>GPS: {coords ? `${coords.latitude.toFixed(5)}, ${coords.longitude.toFixed(5)}` : "Locating…"}{"\n"}Captured: {new Date().toLocaleString()}</Text>{schema.questions.map(renderQuestion)}<Button title="Submit survey" onPress={submit} /></GlassCard></View><Modal visible={cameraOpen} animationType="slide"><CameraView style={{ flex: 1 }} facing="back" ref={cameraRef}><View style={styles.camera}><Button title="Capture photo" onPress={() => capture(cameraRef.current)} /><Button title="Cancel" onPress={() => setCameraOpen(false)} /></View></CameraView></Modal></Screen>;
}
export function DashboardScreen({ navigation }: TabProps<"Dashboard">) { const [counts, setCounts] = useState<{ total: number; pending: number; completed: number; photos: number }>(); const load = useCallback(() => { dashboardCounts().then(value => { if (value) setCounts(value); }); }, []); useEffect(load, [load]); return <Screen><Text style={styles.hero}>Today’s overview</Text><View style={styles.grid}>{[["Total Structures", counts?.total ?? 0], ["Pending Sync", counts?.pending ?? 0], ["Completed", counts?.completed ?? 0], ["Total Photos", counts?.photos ?? 0]].map(([label, value]) => <GlassCard key={label as string} style={styles.metric}><Text style={styles.number}>{value}</Text><Text>{label}</Text></GlassCard>)}</View><Button title="Start new survey" onPress={() => navigation.getParent()?.navigate("SurveyType")} /></Screen>; }
export function SurveyListScreen(_: TabProps<"Surveys">) { const [list, setList] = useState<(SurveyRecord & { responses_json: string })[]>([]); const [search, setSearch] = useState(""); useEffect(() => { records().then(setList); }, []); return <Screen><Field placeholder="Search category or chainage" value={search} onChangeText={setSearch} /><FlatList scrollEnabled={false} data={list.filter(r => `${r.category} ${r.chainage}`.toLowerCase().includes(search.toLowerCase()))} keyExtractor={r => r.id} renderItem={({ item }) => <GlassCard style={styles.item}><Text style={styles.choiceText}>{item.category}</Text><Text>Chainage {item.chainage || "—"} · {item.status}</Text><Text style={styles.meta}>{item.syncStatus}</Text></GlassCard>} /></Screen>; }
export function SyncScreen(_: TabProps<"Sync">) { const [message, setMessage] = useState("Ready to sync."); const run = async () => { setMessage("Syncing…"); const result = await syncPending(); setMessage(result.error ?? `${result.synced} record(s) synced.`); }; return <Screen><GlassCard><Text style={styles.hero}>Sync center</Text><Text style={styles.meta}>{message}</Text><Button title="Sync Now" onPress={run} /></GlassCard></Screen>; }
export function SettingsScreen({ navigation }: TabProps<"Settings">) { const { isDark, toggleTheme } = useTheme(); const [url, setUrl] = useState(""); useEffect(() => { apiBaseUrl().then(setUrl); }, []); return <Screen><GlassCard><Text style={styles.hero}>Settings</Text><View style={styles.setting}><Text>Dark mode</Text><Switch value={isDark} onValueChange={toggleTheme} /></View><Label>API base URL</Label><Field value={url} onChangeText={setUrl} autoCapitalize="none" /><Button title="Save API URL" onPress={() => setApiBaseUrl(url)} /><View style={{ height: 12 }} /><Button title="Log out" onPress={async () => { await logout(); navigation.getParent()?.navigate("Login"); }} /></GlassCard></Screen>; }
const styles = StyleSheet.create({ screen: { flex: 1 }, content: { padding: 20, gap: 14, paddingBottom: 40 }, hero: { fontSize: 24, fontWeight: "800", color: "#1B3A5C", marginBottom: 12 }, choice: { marginBottom: 12, minHeight: 92, justifyContent: "center" }, choiceText: { color: "#1B3A5C", fontWeight: "800", fontSize: 17 }, category: { paddingVertical: 18, marginBottom: 8 }, meta: { color: "#55708C", lineHeight: 21, marginBottom: 12 }, grid: { flexDirection: "row", flexWrap: "wrap", gap: 12 }, metric: { width: "47%", minHeight: 125, justifyContent: "center" }, number: { fontSize: 34, fontWeight: "800", color: "#1B4F8C" }, formRow: { flexDirection: "row", gap: 10 }, rail: { width: 6, backgroundColor: "rgba(111,168,62,.18)", borderRadius: 4, overflow: "hidden" }, railFill: { width: "100%", backgroundColor: "#6FA83E" }, form: { flex: 1 }, options: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 14 }, pill: { borderWidth: 1, borderColor: "#B8CCE1", borderRadius: 20, paddingHorizontal: 12, paddingVertical: 8 }, selected: { backgroundColor: "#CFE5BA", borderColor: "#6FA83E" }, camera: { marginTop: "auto", padding: 24, gap: 12 }, item: { marginBottom: 10 }, setting: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 16 } });
